# Generated by Django 4.0.1 on 2022-01-18 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albaranes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_albaran', models.DateField(default=datetime.datetime(2022, 1, 18, 21, 7, 51, 9803, tzinfo=utc), verbose_name='Fecha albarán')),
                ('no_albaran', models.CharField(max_length=10, unique_for_year='fecha', verbose_name='Número de albarán')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contactos.empresa', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Albarán',
                'verbose_name_plural': 'Albaranes',
            },
        ),
        migrations.CreateModel(
            name='ItemsAlbaranes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField(max_length=200, verbose_name='Concepto')),
                ('unidad', models.CharField(choices=[('kg', 'kilos'), ('ud', 'Unidades'), ('l', 'litros'), ('m3', 'metros cúbicos'), ('ml', 'metros lineales'), ('', 'Sin unidades')], max_length=3, verbose_name='Unidad')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Cantidad')),
                ('p_unit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio unitario')),
                ('tipo_iva', models.DecimalField(choices=[(0, '0%'), (4, '4%'), (10, '10%'), (21, '21%')], decimal_places=2, max_digits=4, null=True, verbose_name='IVA')),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='albaranes.albaranes', verbose_name='Albarán')),
            ],
            options={
                'verbose_name': 'Item Albaranes',
                'verbose_name_plural': 'Items Albaranes',
            },
        ),
    ]
