# Generated by Django 4.0.1 on 2022-01-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField(auto_now_add=True, verbose_name='Fecha albarán')),
                ('no_factura', models.CharField(max_length=20, unique_for_year='fecha', verbose_name='Número de factura')),
                ('tipo', models.CharField(choices=[('ORD', 'Factura ordinaria'), ('RET', 'Factura rectificativa'), ('REC', 'Factura recapitulativa'), ('PRO', 'Factura proforma')], default='FOR', max_length=3, verbose_name='Serie')),
                ('base_imp', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Base Imponible')),
                ('cuota_iva', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cuota IVA')),
                ('tipo_irpf', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Tipo IRPF')),
                ('cuota_irpf', models.DecimalField(choices=[(0, 'No aplica'), (-0.07, '7%'), (-0.15, '15%')], decimal_places=2, max_digits=3, verbose_name='Cuota IRPF')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Importe Total')),
                ('pagado', models.BooleanField(default=False, verbose_name='Factura Pagada')),
                ('forma_pago', models.CharField(choices=[('transferencia a la vista', 'Transferencia a la vista'), ('transferencia 15 días', 'Transferencia 15 días'), ('transferencia 30 días', 'Transferencia 30 días')], max_length=40, verbose_name='Forma de pago')),
                ('cuenta_abono', models.CharField(choices=[('cuenta de prueba', 'Cuenta'), ('efectivo', 'Efectivo')], max_length=25, verbose_name='Cuenta de abono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contactos.empresa', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Albarán',
                'verbose_name_plural': 'Albaranes',
            },
        ),
    ]
